<script setup lang="ts">
import { computed, ref } from 'vue';
import type { Session } from '@remote/shared';
import SessionItem from './SessionItem.vue';
const p = defineProps<{ sessions: Session[]; activeId?: string; loading: boolean; error: string; busy: boolean }>();
defineEmits<{ select: [session: Session]; refresh: []; pin: [session: Session]; archive: [session: Session]; rename: [session: Session]; create: []; createInCwd: [cwd: string]; manualCreate: []; settings: [] }>();
const query = ref(''); const view = ref<'active' | 'archived'>('active'); const collapsed = ref(new Set<string>());
const groups = computed(() => { const q = query.value.trim().toLowerCase(); const filtered = p.sessions.filter(s => (view.value === 'archived' ? s.status === 'archived' : s.status !== 'archived') && (!q || `${s.title} ${s.cwd}`.toLowerCase().includes(q))); const map = new Map<string, Session[]>(); for (const session of filtered) { const key = session.cwd || '未知目录'; map.set(key, [...(map.get(key) || []), session]); } return [...map.entries()].map(([cwd, sessions]) => ({ cwd, sessions })); });
const folder = (path: string) => path.replace(/[\\/]+$/, '').split(/[\\/]/).pop() || path;
function toggle(path: string) { const next = new Set(collapsed.value); next.has(path) ? next.delete(path) : next.add(path); collapsed.value = next; }
</script>

<template>
  <div class="sidebar">
    <header class="brand"><img class="brand-mark" src="/icon.svg" alt=""><div><strong>Codex Remote</strong><small>个人工作区</small></div><button class="icon-button settings-btn" title="设置" @click="$emit('settings')"><svg viewBox="0 0 24 24" width="16" height="16" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 1 1-2.83 2.83l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-4 0v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 1 1-2.83-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1 0-4h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 1 1 2.83-2.83l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 4 0v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 1 1 2.83 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 0 4h-.09a1.65 1.65 0 0 0-1.51 1z"/></svg></button></header>
    <div class="new-thread-row">
      <button type="button" class="new-thread" :disabled="busy" @click="$emit('create')"><span>+</span> 新建会话</button>
      <button type="button" class="new-thread-manual icon-button" title="选择目录新建" :disabled="busy" @click="$emit('manualCreate')"><svg viewBox="0 0 24 24" width="15" height="15" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M3.5 6.5h6l2 2h9v10h-17z"/><path d="M3.5 8.5v-3h6l2 3"/></svg></button>
    </div>
    <label class="search"><span>⌕</span><input v-model="query" placeholder="搜索会话或目录" aria-label="搜索会话"></label>
    <div class="session-tabs"><button :class="{ active: view === 'active' }" @click="view = 'active'">项目</button><button :class="{ active: view === 'archived' }" @click="view = 'archived'">已归档</button><button class="icon-button" :disabled="loading" title="刷新" @click="$emit('refresh')">↻</button></div>
    <div v-if="loading && !sessions.length" class="sidebar-state">正在发现 Codex 会话…</div><div v-else-if="error && !sessions.length" class="sidebar-state error">{{ error }}<button @click="$emit('refresh')">重试</button></div><div v-else-if="!groups.length" class="sidebar-state">{{ query ? '没有匹配会话' : view === 'archived' ? '没有已归档会话' : '尚无会话' }}</div>
    <div v-else class="session-list grouped"><section v-for="group in groups" :key="group.cwd" class="session-group" :class="{ collapsed: collapsed.has(group.cwd) }"><div class="project-header-row"><button class="project-header" :title="group.cwd" @click="toggle(group.cwd)"><svg v-if="collapsed.has(group.cwd)" class="folder-svg" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 6.5h6l2 2h9v10h-17z"/><path d="M3.5 8.5v-3h6l2 3"/></svg><svg v-else class="folder-svg open" viewBox="0 0 24 24" aria-hidden="true"><path d="M3.5 7.5v-2h6l2 3h9v2"/><path d="M4.5 10.5h17l-2.4 8H2.6z"/></svg><strong>{{ folder(group.cwd) }}</strong><small class="project-count">{{ group.sessions.length }}</small></button><button class="project-new-thread" :title="`在 ${folder(group.cwd)} 新建会话`" :disabled="busy" @click.stop="$emit('createInCwd', group.cwd)"><svg viewBox="0 0 24 24" width="14" height="14" fill="none" stroke="currentColor" stroke-width="2.2" stroke-linecap="round"><path d="M12 5v14M5 12h14"/></svg></button></div><div v-show="!collapsed.has(group.cwd)" class="project-children"><SessionItem v-for="s in group.sessions" :key="s.session_id" :session="s" :selected="s.session_id === activeId" @select="$emit('select', s)" @pin="$emit('pin', s)" @archive="$emit('archive', s)" @rename="$emit('rename', s)"/></div></section></div>
    <footer class="sidebar-footer"><span class="status-dot online"></span><span>Codex</span><small>{{ sessions.length }} 个会话</small></footer>
  </div>
</template>
