<script setup lang="ts">
import{ref,onMounted,watch}from'vue';import{api,ApiError}from'../api';import{hasOfflinePassword,setOfflinePassword,clearOfflinePassword,offlinePasswordIsValid}from'../composables/offlineAccess';
const p=defineProps<{open:boolean;theme:string;offlineMode?:boolean}>();const emit=defineEmits<{close:[];theme:[value:string];unpair:[];exitOffline:[]}>();
const pairPwdStatus=ref<boolean|undefined>(undefined),newPwd=ref(''),pwdBusy=ref(false),pwdError=ref(''),pwdOk=ref('');
// Offline access password state
const offlinePwdStatus=ref<boolean|undefined>(undefined),newOfflinePwd=ref(''),offlinePwdBusy=ref(false),offlinePwdError=ref(''),offlinePwdOk=ref('');
async function loadStatus(){try{pairPwdStatus.value=(await api.pairStatus()).password}catch{pairPwdStatus.value=undefined}}
async function loadOfflineStatus(){try{offlinePwdStatus.value=await hasOfflinePassword()}catch{offlinePwdStatus.value=undefined}}
watch(()=>p.open,value=>{if(value)loadOfflineStatus()});
async function setPwd(){if(pwdBusy.value)return;pwdError.value='';pwdOk.value='';if(newPwd.value.trim().length<8){pwdError.value='密码至少 8 位';return}pwdBusy.value=true;try{await api.setPairPassword(newPwd.value.trim());newPwd.value='';pwdOk.value='已保存配对密码';pwdError.value='';await loadStatus()}catch(e){pwdError.value=e instanceof ApiError&&e.status===403?'仅可从电脑本机设置':e instanceof Error?e.message:'保存失败';pwdOk.value=''}finally{pwdBusy.value=false}}
async function clearPwd(){if(pwdBusy.value)return;pwdError.value='';pwdOk.value='';pwdBusy.value=true;try{await api.clearPairPassword();pwdOk.value='已清除配对密码';pwdError.value='';await loadStatus()}catch(e){pwdError.value=e instanceof ApiError&&e.status===403?'仅可从电脑本机设置':e instanceof Error?e.message:'清除失败';pwdOk.value=''}finally{pwdBusy.value=false}}
async function setOfflinePwd(){if(offlinePwdBusy.value)return;offlinePwdError.value='';offlinePwdOk.value='';const pw=newOfflinePwd.value.trim();if(!offlinePasswordIsValid(pw)){offlinePwdError.value='离线密码至少 8 位';return}offlinePwdBusy.value=true;try{await setOfflinePassword(pw);newOfflinePwd.value='';offlinePwdOk.value='已保存离线访问密码';offlinePwdError.value='';await loadOfflineStatus()}catch(e){offlinePwdError.value=e instanceof Error?e.message:'保存失败';offlinePwdOk.value=''}finally{offlinePwdBusy.value=false}}
async function clearOfflinePwd(){if(offlinePwdBusy.value)return;offlinePwdError.value='';offlinePwdOk.value='';offlinePwdBusy.value=true;try{await clearOfflinePassword();offlinePwdOk.value='已清除离线访问密码';offlinePwdError.value='';await loadOfflineStatus()}catch(e){offlinePwdError.value=e instanceof Error?e.message:'清除失败';offlinePwdOk.value=''}finally{offlinePwdBusy.value=false}}
onMounted(()=>{loadStatus();loadOfflineStatus()});
</script>
<template><div v-if="open" class="viewer-backdrop" @click.self="$emit('close')"><section class="settings-surface"><header><div><small>设备与外观</small><h2>设置</h2></div><button class="icon-button" @click="$emit('close')">×</button></header><label>主题<select :value="theme" @change="$emit('theme',($event.target as HTMLSelectElement).value)"><option value="system">跟随系统</option><option value="light">浅色</option><option value="dark">深色</option></select></label>
<div class="settings-row password-config-row"><div><strong>配对密码</strong><small>本机设置后，远程端可用密码配对并跨电脑重启自动重连。{{pairPwdStatus===true?'当前：已设置':pairPwdStatus===false?'当前：未设置':''}}</small><div class="password-input"><input v-model.trim="newPwd" type="password" placeholder="新密码（至少 8 位）" :disabled="pwdBusy" @keyup.enter="setPwd"><button class="text-button" :disabled="pwdBusy||newPwd.length<8" @click="setPwd">{{pwdBusy?'保存中…':'设置'}}</button><button v-if="pairPwdStatus" class="text-button danger-text" :disabled="pwdBusy" @click="clearPwd">清除</button></div><p v-if="pwdError" class="form-error">{{pwdError}}</p><p v-else-if="pwdOk" class="form-ok">{{pwdOk}}</p></div></div>
<div class="settings-row password-config-row"><div><strong>离线访问密码</strong><small>设置后，手机端可在本地服务未开启时凭此密码查看缓存的历史对话。{{offlinePwdStatus===true?'当前：已设置':offlinePwdStatus===false?'当前：未设置':''}}</small><div class="password-input"><input v-model.trim="newOfflinePwd" type="password" placeholder="新离线密码（至少 8 位）" :disabled="offlinePwdBusy" @keyup.enter="setOfflinePwd"><button class="text-button" :disabled="offlinePwdBusy||newOfflinePwd.length<8" @click="setOfflinePwd">{{offlinePwdBusy?'保存中…':'设置'}}</button><button v-if="offlinePwdStatus" class="text-button danger-text" :disabled="offlinePwdBusy" @click="clearOfflinePwd">清除</button></div><p v-if="offlinePwdError" class="form-error">{{offlinePwdError}}</p><p v-else-if="offlinePwdOk" class="form-ok">{{offlinePwdOk}}</p></div></div>
<div v-if="offlineMode" class="settings-row"><div><strong>离线模式</strong><small>当前正在离线查看缓存对话。返回配对可重新连接服务。</small></div><button class="danger-button" @click="$emit('exitOffline')">退出离线模式</button></div>
<div class="settings-row"><div><strong>已配对设备</strong><small>凭据仅用于本机连接，界面不会显示令牌。</small></div><button class="danger-button" @click="$emit('unpair')">解除配对</button></div>
<div class="settings-row"><div><strong>Codex-only</strong><small>此客户端不提供其他 provider 或终端工具箱。</small></div></div></section></div></template>
