import{describe,expect,it}from'vitest';import type{Pending}from'./db';import{DeferredSendError,isPendingCancellable,mergePendingMessages,pendingToMessage,replayInSessionOrder}from'./composables/outbox';
const item=(id:string,session_id:string,created_at:string):Pending=>({id,session_id,created_at,content:id,status:'pending'});
describe('outbox replay',()=>{it('preserves per-session order, client ids and blocks a failed session only',async()=>{const seen:string[]=[];const items=[item('b2','b','2'),item('a2','a','2'),item('a1','a','1'),item('b1','b','1')];await replayInSessionOrder(items,async value=>{seen.push(`${value.session_id}:${value.id}`);if(value.id==='a1')throw new Error('offline')},async()=>{});expect(seen).toEqual(['a:a1','b:b1','b:b2']);expect(items.find(x=>x.id==='a1')?.status).toBe('failed');expect(items.find(x=>x.id==='a2')?.status).toBe('pending');expect(items.find(x=>x.id==='b2')?.status).toBe('sent')});
it('skips already-sent items',async()=>{const seen:string[]=[];const items=[item('s1','a','1'),item('p1','a','2')];items[0].status='sent';await replayInSessionOrder(items,async value=>{seen.push(value.id)},async()=>{});expect(seen).toEqual(['p1']);expect(items.find(x=>x.id==='p1')?.status).toBe('sent')});
 it('keeps a busy thread queued and resumes it on the next replay',async()=>{const seen:string[]=[];const items=[item('a1','a','1'),item('a2','a','2'),item('b1','b','1')];let busy=true;await replayInSessionOrder(items,async value=>{seen.push(`${value.session_id}:${value.id}`);if(value.id==='a1'&&busy)throw new DeferredSendError()},async()=>{});expect(seen).toEqual(['a:a1','b:b1']);expect(items.find(x=>x.id==='a1')?.status).toBe('waiting');expect(items.find(x=>x.id==='a2')?.status).toBe('pending');busy=false;await replayInSessionOrder(items,async value=>{seen.push(`${value.session_id}:${value.id}`)},async()=>{});expect(seen).toEqual(['a:a1','b:b1','a:a1','a:a2']);expect(items.filter(x=>x.session_id==='a').every(x=>x.status==='sent')).toBe(true)});
it('returns empty for all-sent items',async()=>{const items=[item('s1','a','1')];items[0].status='sent';const result=await replayInSessionOrder(items,async()=>{},async()=>{});expect(result).toHaveLength(0)})});
describe('pending message projection',()=>{
 it('projects queued content and references into its target conversation',()=>{const queued:Pending={...item('q1','session-a','2026-01-01T00:00:02Z'),content:'待发送内容',input:[{type:'skill',name:'review',path:'C:/skills/review/SKILL.md'}]};const messages=mergePendingMessages([{msg_id:'a1',session_id:'session-a',role:'assistant',content:'旧回复',timestamp:'2026-01-01T00:00:01Z',seq:1}],[queued],'session-a');expect(messages).toHaveLength(2);expect(messages[1]).toMatchObject({msg_id:'local:q1',client_id:'q1',content:'待发送内容'});expect(messages[1].references?.[0]).toMatchObject({type:'skill',label:'review'})});
 it('does not project a queued item into another conversation',()=>{const queued=item('q1','session-a','1');expect(mergePendingMessages([], [queued], 'session-b')).toHaveLength(0)});
 it('keeps sent items visible until the canonical message arrives',()=>{const queued=item('q1','session-a','1');queued.status='sent';expect(pendingToMessage(queued).msg_id).toBe('local:q1');expect(mergePendingMessages([], [queued], 'session-a')).toHaveLength(1)});
 it('only allows cancellation before submission starts',()=>{const queued=item('q1','session-a','1');expect(isPendingCancellable(queued)).toBe(true);queued.status='sending';expect(isPendingCancellable(queued)).toBe(false);queued.status='sent';expect(isPendingCancellable(queued)).toBe(false)});
});
describe('cancellation during replay',()=>{
 it('skips an item cancelled before send',async()=>{const queued=item('q1','session-a','1');const sent:string[]=[];const cancelled=new Set(['q1']);await replayInSessionOrder([queued],async value=>{sent.push(value.id)},async()=>{},value=>cancelled.has(value.id));expect(sent).toEqual([]);expect(queued.status).toBe('pending')});
});
