import {EventEmitter} from 'node:events';
import {afterEach,describe,expect,it,vi} from 'vitest';
import {join} from 'node:path';
import {mkdir,rm,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {randomUUID} from 'node:crypto';
import {Store} from '../db.js';
import {loadConfig} from '../config.js';
import {CodexManager} from './manager.js';
import {RpcRemoteError} from './json-rpc-client.js';
let manager:CodexManager|undefined,store:Store|undefined,codexHome='';
afterEach(async()=>{vi.unstubAllGlobals();await manager?.close();store?.close();if(codexHome)await rm(codexHome,{recursive:true,force:true});codexHome=''});
describe('Codex app-server bridge',()=>{it('handshakes, streams events, correlates approvals and interrupts',async()=>{store=new Store(':memory:');const root=process.cwd();const config=loadConfig({databasePath:':memory:',secret:'x'.repeat(32),codexCommand:process.execPath,codexArgs:[join(root,'src/test-fixtures/fake-app-server.mjs')],appServerCwd:root,codexCwdAllowlist:[root],codexRequestTimeoutMs:1000});manager=new CodexManager(config,store);expect(await manager.list()).toHaveLength(1);const created=await manager.start(root);expect(created.id).toMatch(/^111/);const turn=await manager.startTurn(created.id,'hi','client-1');expect(turn.turn_id).toBe('turn-1');await new Promise(r=>setTimeout(r,20));expect(store.eventsAfter(0).map(e=>e.type)).toEqual(['turn_started','user_message','assistant_delta','approval_requested']);expect(store.eventsAfter(0).find(event=>event.type==='user_message')?.metadata?.client_id).toBe('client-1');const approval=store.listApprovals(created.id)[0];expect(approval).toMatchObject({kind:'item/commandExecution/requestApproval',status:'pending'});expect(approval.request_id).toMatch(/:approval-1$/);expect(manager.decide(approval.request_id,'accept')).toMatchObject({status:'resolved',decision:'accept'});await new Promise(r=>setTimeout(r,20));expect(store.eventsAfter(0).at(-1)?.content).toBe('approval:accept');expect(()=>manager!.decide(approval.request_id,'decline')).toThrow(/already resolved/);expect(await manager.interrupt(created.id)).toMatchObject({status:'interrupt_requested'})});
it('searches files via fuzzyFileSearch',async()=>{store=new Store(':memory:');const root=process.cwd();const config=loadConfig({databasePath:':memory:',secret:'x'.repeat(32),codexCommand:process.execPath,codexArgs:[join(root,'src/test-fixtures/fake-app-server.mjs')],appServerCwd:root,codexCwdAllowlist:[root],codexRequestTimeoutMs:1000});manager=new CodexManager(config,store);const results=await manager.fileSearch('readme',[root]);expect(results).toHaveLength(2);expect(results[0].file_name).toBe('README.md');expect(results[0].match_type).toBe('file')});
it('restarts the app-server connection once after a thread writer conflict',async()=>{store=new Store(':memory:');const root=process.cwd();const config=loadConfig({databasePath:':memory:',secret:'x'.repeat(32),appServerCwd:root,codexCwdAllowlist:[root]});const thread={id:'11111111-1111-4111-8111-111111111111',cwd:root,createdAt:1,updatedAt:1};let resumes=0,closes=0;class FakeRpc extends EventEmitter{async request(method:string){if(method==='initialize')return {};if(method==='thread/resume'){resumes+=1;if(resumes===1)throw new RpcRemoteError(`thread ${thread.id} already has an active writer`);return {thread}}if(method==='turn/start')return {turn:{id:'turn-recovered'}};throw new Error(`unexpected ${method}`)}notify(){}async close(){closes+=1}}const rpc=new FakeRpc();manager=new CodexManager(config,store,rpc as any);await expect(manager.startTurn(thread.id,'hello','client-1')).resolves.toMatchObject({turn_id:'turn-recovered'});expect(resumes).toBe(2);expect(closes).toBe(1)});
});

it('loads paginated visible models from app-server and emits capability invalidations',async()=>{store=new Store(':memory:');const root=process.cwd();codexHome=join(tmpdir(),`codex-models-${randomUUID()}`);await mkdir(codexHome,{recursive:true});await writeFile(join(codexHome,'models_cache.json'),JSON.stringify({models:[{slug:'gpt-5.4-mini'}]}));const config=loadConfig({databasePath:':memory:',secret:'x'.repeat(32),codexHome,codexCommand:process.execPath,codexArgs:[join(root,'src/test-fixtures/fake-app-server.mjs')],appServerCwd:root,codexCwdAllowlist:[root],codexRequestTimeoutMs:1000});const requests:string[]=[];class FakeRpc extends EventEmitter{async request(method:string,params:any){requests.push(method);if(method==='initialize')return {};if(method==='model/list')return params.cursor?{data:[{id:'gpt-hidden',model:'gpt-hidden',hidden:true},{id:'gpt-second',model:'gpt-second',displayName:'Second',supportedReasoningEfforts:[{reasoningEffort:'ultra'}]}],nextCursor:null}:{data:[{id:'gpt-first',model:'gpt-first',displayName:'First',isDefault:true,supportedReasoningEfforts:[{reasoningEffort:'max'}]}],nextCursor:'next'};throw new Error(`unexpected ${method}`)}notify(){}async close(){}}const rpc=new FakeRpc();manager=new CodexManager(config,store,rpc as any);const invalidations:any[]=[];manager.on('capabilities',value=>invalidations.push(value));await expect(manager.models()).resolves.toEqual([expect.objectContaining({model:'gpt-first',supportedReasoningEfforts:['max']}),expect.objectContaining({model:'gpt-second',supportedReasoningEfforts:['ultra']})]);expect(requests).toContain('model/list');rpc.emit('notification',{method:'account/updated',params:{}});expect(invalidations).toEqual([['models','apps','defaults']])});

it('filters app-server models to the provider /v1/models allowlist',async()=>{store=new Store(':memory:');const root=process.cwd();codexHome=join(tmpdir(),`codex-provider-${randomUUID()}`);await mkdir(codexHome,{recursive:true});await writeFile(join(codexHome,'config.toml'),['model_provider = "relay"','','[model_providers.relay]','base_url = "https://models.example/v1"'].join('\n'));vi.stubGlobal('fetch',vi.fn().mockResolvedValue({ok:true,json:async()=>({data:[{id:'provider-a'},{id:'provider-b',display_name:'Provider B'}]})}));const config=loadConfig({databasePath:':memory:',secret:'x'.repeat(32),codexHome,codexCommand:process.execPath,codexArgs:[join(root,'src/test-fixtures/fake-app-server.mjs')],appServerCwd:root,codexCwdAllowlist:[root],codexRequestTimeoutMs:1000});class FakeRpc extends EventEmitter{async request(method:string){if(method==='initialize')return {};if(method==='model/list')return {data:[{id:'gpt-5.6',model:'gpt-5.6'},{id:'gpt-5.5',model:'gpt-5.5'},{id:'gpt-5.2',model:'gpt-5.2'},{id:'provider-a',model:'provider-a',displayName:'Provider A Remote',supportedReasoningEfforts:[{reasoningEffort:'high'}]}],nextCursor:null};throw new Error(`unexpected ${method}`)}notify(){}async close(){}}manager=new CodexManager(config,store,new FakeRpc() as any);await expect(manager.models()).resolves.toEqual([expect.objectContaining({model:'provider-a',displayName:'Provider A Remote',supportedReasoningEfforts:['high']}),expect.objectContaining({model:'provider-b',displayName:'Provider B'})])});
