import { EventEmitter } from 'node:events';
import { resolve,relative,isAbsolute } from 'node:path';
import { readFile,realpath } from 'node:fs/promises';
import { join } from 'node:path';
import type { Config } from '../config.js';
import type { Store } from '../db.js';
import { AppServerProcess } from './app-server-process.js';
import { JsonRpcClient,RpcUnavailableError } from './json-rpc-client.js';
import { METHODS,APPROVAL_KINDS,ApprovalNotSupportedError,approvalResult,type ApprovalDecision,type CodexThread,type ThreadListResponse,type ThreadResponse,type TurnResponse,record } from './protocol.js';
import { routeNotification } from './notification-router.js';
import type { AppOption,CodexDefaults,FileSearchResult,ModelOption,RuntimeConfig,SkillOption,UserInput } from '@remote/shared';
import { discoverApps,discoverModels,discoverSkills } from '../local-capabilities.js';

export class CodexManager extends EventEmitter {
 readonly rpc:JsonRpcClient;private initialized?:Promise<void>;private queues=new Map<string,Promise<unknown>>();private resumed=new Set<string>();private active=new Map<string,string>();private epoch=Date.now();
 constructor(private config:Config,private store:Store,rpc?:JsonRpcClient){super();this.store.expireApprovalsBefore(this.epoch);this.rpc=rpc??new JsonRpcClient(new AppServerProcess(config.codexCommand,config.codexArgs,config.appServerCwd),config.codexRequestTimeoutMs);this.rpc.on('notification',(m:any)=>this.notification(m.method,m.params));this.rpc.on('serverRequest',(m:any)=>this.serverRequest(m));this.rpc.on('unavailable',()=>{this.initialized=undefined;this.resumed.clear();this.active.clear();this.epoch+=1;this.store.expireApprovalsBefore(this.epoch)});this.rpc.on('malformed',(line:string)=>this.emit('debug',{kind:'malformed_json',line}));}
 private async ready(){if(!this.initialized)this.initialized=(async()=>{await this.rpc.request(METHODS.initialize,{clientInfo:{name:'codex-remote',title:'Codex Remote',version:'0.1.0'},capabilities:null});this.rpc.notify(METHODS.initialized,{})})().catch(e=>{this.initialized=undefined;throw e});return this.initialized}
 async list(archived=false):Promise<CodexThread[]>{await this.ready();let cursor:string|null=null;const all:CodexThread[]=[];do{const r:ThreadListResponse=await this.rpc.request<ThreadListResponse>(METHODS.threadList,{cursor,limit:100,sortKey:'updated_at',archived});all.push(...(r.data??[]));cursor=r.nextCursor??null}while(cursor);return all}
 async read(id:string){await this.ready();return (await this.rpc.request<ThreadResponse>(METHODS.threadRead,{threadId:id,includeTurns:true})).thread}
 async start(cwd:string,runtime:RuntimeConfig={}){await this.ready();const safe=await this.validateCwd(cwd);const thread=(await this.rpc.request<ThreadResponse>(METHODS.threadStart,{cwd:safe,...threadRuntime(runtime)})).thread;this.resumed.add(thread.id);this.store.ensureSession(thread);return thread}
 async resume(id:string,cwd?:string){await this.ready();if(this.resumed.has(id))return;const params:any={threadId:id};if(cwd)params.cwd=await this.validateCwd(cwd);const thread=(await this.rpc.request<ThreadResponse>(METHODS.threadResume,params)).thread;this.resumed.add(id);this.store.ensureSession(thread)}
 startTurn(id:string,input:UserInput[]|string,runtime:RuntimeConfig|string={},clientId?:string){const items=typeof input==='string'?[{type:'text' as const,text:input}]:input;const config=typeof runtime==='string'?{}:runtime;const requestId=typeof runtime==='string'?runtime:clientId;return this.serial(id,async()=>{await this.resume(id);if(this.active.has(id))throw Object.assign(new Error('thread already has an active turn'),{status:409});const result=await this.rpc.request<TurnResponse>(METHODS.turnStart,{threadId:id,clientUserMessageId:requestId,input:items.map(item=>item.type==='text'?{...item,text_elements:[]}:item),...turnRuntime(config)});this.active.set(id,result.turn.id);return {thread_id:id,turn_id:result.turn.id,status:'started'}})}
 async interrupt(id:string){await this.ready();const turnId=this.active.get(id);if(!turnId)throw Object.assign(new Error('no active turn'),{status:409});await this.rpc.request(METHODS.turnInterrupt,{threadId:id,turnId});return {thread_id:id,turn_id:turnId,status:'interrupt_requested'}}
 async models():Promise<ModelOption[]>{const local=await discoverModels(this.config.codexHome);try{await this.ready();const r:any=await this.rpc.request(METHODS.modelList,{});return mergeBy(local,(r.data??[]).filter((m:any)=>!m.hidden).map((m:any)=>({id:String(m.id??m.model),model:String(m.model??m.id),displayName:String(m.displayName??m.model??m.id),description:m.description,isDefault:Boolean(m.isDefault),defaultReasoningEffort:m.defaultReasoningEffort,supportedReasoningEfforts:(m.supportedReasoningEfforts??[]).map((x:any)=>String(x.reasoningEffort)),inputModalities:m.inputModalities??[]})),x=>x.model)}catch{return local}}
 async skills(cwd:string):Promise<SkillOption[]>{const local=await discoverSkills(this.config.codexHome);try{await this.ready();const safe=await this.validateCwd(cwd);const r:any=await this.rpc.request(METHODS.skillsList,{cwds:[safe]});return mergeBy(local,(r.data??[]).flatMap((x:any)=>x.skills??[]).map((s:any)=>({name:String(s.name),description:String(s.description??s.shortDescription??''),path:String(s.path),scope:s.scope,enabled:s.enabled!==false})),x=>x.path)}catch{return local}}
 async apps(threadId?:string):Promise<AppOption[]>{const local=await discoverApps(this.config.codexHome);try{await this.ready();let cursor:null|string=null;const out:AppOption[]=[];do{const r:any=await this.rpc.request(METHODS.appList,{cursor,limit:100,threadId});out.push(...(r.data??[]).map((a:any)=>({id:String(a.id),name:String(a.name),description:a.description??undefined,logoUrl:a.logoUrl??undefined,isAccessible:Boolean(a.isAccessible),isEnabled:Boolean(a.isEnabled)})));cursor=r.nextCursor??null}while(cursor);return mergeBy(local,out,x=>x.id)}catch{return local}}
 async defaults():Promise<CodexDefaults>{try{await this.ready();const r:any=await this.rpc.request(METHODS.configRead,{includeLayers:false});return defaultsFromRecord(r.config??{})}catch{return this.fileDefaults()}}
 private async fileDefaults():Promise<CodexDefaults>{try{return defaultsFromRecord(parseTopLevelToml(await readFile(join(this.config.codexHome,'config.toml'),'utf8')))}catch{return {}}}
 async archive(id:string,archived:boolean){await this.ready();await this.rpc.request(archived?METHODS.threadArchive:METHODS.threadUnarchive,{threadId:id})}
 async rename(id:string,name:string){await this.ready();await this.rpc.request(METHODS.threadNameSet,{threadId:id,name})}
 private serial<T>(id:string,fn:()=>Promise<T>):Promise<T>{const prior=this.queues.get(id)??Promise.resolve();const next=prior.catch(()=>{}).then(fn);const tracked=next.then(()=>undefined,()=>undefined);this.queues.set(id,tracked);void tracked.then(()=>{if(this.queues.get(id)===tracked)this.queues.delete(id)});return next}
 private notification(method:string,params:unknown){const event=routeNotification(method,params);if(event){const saved=this.store.addEvent(event);if(saved.type==='turn_started'){const p=record(params);this.active.set(saved.session,String(record(p.turn).id??p.turnId??''))}if(saved.type==='turn_completed'||saved.type==='turn_failed')this.active.delete(saved.session);this.emit('event',saved)}else this.emit('debug',{kind:'unknown_notification',method})}
 private serverRequest(message:any){const p=record(message.params),thread=String(p.threadId??p.conversationId??record(p.thread).id??''),turn=String(p.turnId??''),item=String(p.itemId??p.callId??'');const kind=String(message.method);if(!APPROVAL_KINDS.has(kind))return this.emit('debug',{kind:'unsupported_server_request',method:message.method});const requestId=`${this.epoch}:${String(message.id)}`;this.store.addApproval({requestId,rawId:message.id,epoch:this.epoch,threadId:thread,turnId:turn,itemId:item,kind,payload:message.params});const saved=this.store.addEvent({id:`approval:${requestId}`,type:'approval_requested',session:thread,timestamp:new Date().toISOString(),metadata:{request_id:requestId,kind,turn_id:turn,item_id:item}});this.emit('event',saved)}
 /**
  * Answers a captured app-server server request. The store transition happens
  * first so a duplicate decision cannot write twice to the same JSON-RPC id,
  * and the pending row is restored when the write fails.
  */
 decide(requestId:string,decision:ApprovalDecision,answers?:Record<string,string[]>){
  const approval=this.store.getApproval(requestId);
  if(!approval)throw Object.assign(new Error('approval request not found'),{status:404});
  if(approval.status!=='pending')throw Object.assign(new Error(`approval request is already ${approval.status}`),{status:409});
  if(approval.epoch!==this.epoch){this.store.expireApprovalsBefore(this.epoch);throw Object.assign(new Error('Codex app-server restarted; this request can no longer be answered'),{status:409})}
  const available=record(approval.payload).availableDecisions;if(Array.isArray(available)&&!available.some(value=>value===decision))throw Object.assign(new Error(`decision ${decision} is not available for this request`),{status:422});
  const result=approvalResult(approval.kind,decision,answers);
  if(!this.store.settleApproval(requestId,decision))throw Object.assign(new Error('approval request is already resolved'),{status:409});
  try{this.rpc.respond(approval.raw_id,result)}catch(error){this.store.revertApproval(requestId);throw error}
  return {request_id:requestId,session_id:approval.session_id,decision,status:'resolved' as const};
 }
 private async validateCwd(cwd:string){let target:string;try{target=await realpath(resolve(cwd))}catch{throw Object.assign(new Error('working directory must exist'),{status:400})}for(const root of this.config.codexCwdAllowlist){let safeRoot:string;try{safeRoot=await realpath(resolve(root))}catch{continue}const r=relative(safeRoot,target);if(r===''||(!r.startsWith('..')&&!isAbsolute(r)))return target}throw Object.assign(new Error('working directory is outside CODEX_CWD_ALLOWLIST'),{status:403})}
 async fileSearch(query:string,roots:string[]):Promise<FileSearchResult[]>{await this.ready();try{const r:any=await this.rpc.request(METHODS.fuzzyFileSearch,{query,roots});return (r.files??[]).map((f:any)=>({path:String(f.path),file_name:String(f.file_name),match_type:f.match_type==='directory'?'directory':'file',score:Number(f.score??0),root:String(f.root??'')}))}catch{return[]}}
 async readDirectory(path:string):Promise<{fileName:string;isDirectory:boolean;isFile:boolean}[]>{await this.ready();try{const r:any=await this.rpc.request(METHODS.fsReadDirectory,{path});return (r.entries??[]).map((e:any)=>({fileName:String(e.fileName),isDirectory:Boolean(e.isDirectory),isFile:Boolean(e.isFile)}))}catch{return[]}}
 async close(){await this.rpc.close()}
}
export {RpcUnavailableError,ApprovalNotSupportedError};
function threadRuntime(r:RuntimeConfig){return {...(r.model?{model:r.model}:{}),...(r.approvalPolicy?{approvalPolicy:r.approvalPolicy}:{}),...(r.sandbox?{sandbox:r.sandbox}:{}),...(r.effort?{config:{model_reasoning_effort:r.effort}}:{})}}
function turnRuntime(r:RuntimeConfig){return {...(r.model?{model:r.model}:{}),...(r.effort?{effort:r.effort}:{}),...(r.approvalPolicy?{approvalPolicy:r.approvalPolicy}:{}),...(r.sandbox?{sandboxPolicy:sandboxPolicy(r.sandbox)}:{})}}
function sandboxPolicy(mode:RuntimeConfig['sandbox']){if(mode==='danger-full-access')return {type:'dangerFullAccess'};if(mode==='read-only')return {type:'readOnly',access:{type:'fullAccess'}};return {type:'workspaceWrite',writableRoots:[],readOnlyAccess:{type:'fullAccess'},networkAccess:true,excludeTmpdirEnvVar:false,excludeSlashTmp:false}}
function value(v:unknown){return typeof v==='string'&&v?v:undefined}
function normalizeSandbox(v:unknown):RuntimeConfig['sandbox']|undefined{const s=value(v)?.replace(/_/g,'-');return s==='read-only'||s==='workspace-write'||s==='danger-full-access'?s:undefined}
function defaultsFromRecord(c:Record<string,unknown>):CodexDefaults{return {model:value(c.model),effort:value(c.model_reasoning_effort) as CodexDefaults['effort'],approvalPolicy:value(c.approval_policy)?.replace(/_/g,'-') as CodexDefaults['approvalPolicy'],sandbox:normalizeSandbox(c.sandbox_mode)}}
function parseTopLevelToml(source:string):Record<string,unknown>{const result:Record<string,unknown>={};let top=true;for(const raw of source.split(/\r?\n/)){const line=raw.replace(/#.*$/,'').trim();if(!line)continue;if(line.startsWith('[')){top=false;continue}if(!top)continue;const match=line.match(/^([A-Za-z0-9_-]+)\s*=\s*(.+)$/);if(!match)continue;result[match[1]]=match[2].trim().replace(/^['"]|['"]$/g,'')}return result}
function mergeBy<T>(local:T[],remote:T[],key:(item:T)=>string):T[]{const result=new Map(local.map(item=>[key(item),item]));for(const item of remote)result.set(key(item),item);return [...result.values()]}
