import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import request from 'supertest';
import { createServer } from 'node:http';
import { mkdir, rm, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { randomUUID } from 'node:crypto';
import Database from 'better-sqlite3';
import { loadConfig } from './config.js';import {cleanConversationText,readRolloutEvents} from './codex-sessions.js';import { Store } from './db.js';import { AuthService } from './auth.js';import { SessionService } from './service.js';import { createApp } from './app.js';
let root='';let store:Store;const id1='11111111-1111-4111-8111-111111111111',id2='22222222-2222-4222-8222-222222222222';const line=(v:unknown)=>JSON.stringify(v)+'\n';
async function rollout(id:string,day:string,cwd:string,user:string,assistant:string){const dir=join(root,'sessions','2026','08',day);await mkdir(dir,{recursive:true});const path=join(dir,`rollout-${id}.jsonl`);await writeFile(path,line({timestamp:`2026-08-${day}T10:00:00Z`,type:'session_meta',payload:{id,cwd,timestamp:`2026-08-${day}T10:00:00Z`}})+line({timestamp:`2026-08-${day}T10:01:00Z`,type:'event_msg',payload:{type:'user_message',message:user}})+line({timestamp:`2026-08-${day}T10:02:00Z`,type:'response_item',payload:{type:'message',role:'assistant',content:[{type:'output_text',text:assistant}]}}));return path}
function fixture(){const config=loadConfig({databasePath:':memory:',secret:'x'.repeat(32),codexHome:root,codexSessionsDir:join(root,'sessions'),codexCommand:join(root,'missing-codex.exe'),codexCwdAllowlist:[root],codexRequestTimeoutMs:100,allowDangerFullAccess:false});store=new Store(':memory:');const auth=new AuthService(store,config);const sessions=new SessionService(store,config);return {api:request(createServer(createApp(store,auth,sessions,config))),auth}}
async function token(f:any){const p=f.auth.createPairCode();const r=await f.api.post('/api/pair/request').send({code:p.code,device_name:'test'});f.device_id=r.body.device_id;f.refresh_token=r.body.refresh_token;return r.body.access_token}
beforeEach(async()=>{root=join(tmpdir(),`codex-remote-${randomUUID()}`);await mkdir(root,{recursive:true})});afterEach(async()=>{store?.close();await rm(root,{recursive:true,force:true})});
describe('Codex rollout API',()=>{
 it('removes runtime injections while preserving the real user request',()=>{const source='<environment_context>\n<cwd>C:\\secret</cwd>\n</environment_context>\n# Chrome tabs:\n- Private tab\n# My request:\n只保留这段问题';expect(cleanConversationText(source)).toBe('只保留这段问题')});
 it('strips recommended_plugins injections from user messages',()=>{const source='<recommended_plugins>\n- Airtable (airtable@openai-curated-remote)\n- Slack (slack@openai-curated-remote)\n</recommended_plugins>\n<app-context>\ncontext\n</app-context>\n# My request:\n只保留这段问题';expect(cleanConversationText(source)).toBe('只保留这段问题')});
 it('projects historical tool calls from rollouts',async()=>{const path=await rollout(id1,'10',root,'Prompt','Answer');await writeFile(path,line({timestamp:'2026-08-10T10:03:00Z',type:'response_item',payload:{type:'mcpToolCall',id:'tool-1',server:'browser',tool:'click',status:'completed',arguments:{ref:'a1'},result:{content:'ok'}}}),{flag:'a'});const events=await readRolloutEvents(path,id1);expect(events).toEqual([expect.objectContaining({type:'tool_call',metadata:expect.objectContaining({server:'browser',tool:'click'})})])});
 it('pairs native rollout tool calls with their output and ignores empty reasoning',async()=>{const path=await rollout(id1,'10',root,'Prompt','Answer');await writeFile(path,line({timestamp:'2026-08-10T10:03:00Z',type:'response_item',payload:{type:'function_call',name:'shell_command',arguments:'{"command":"pwd"}',call_id:'call-1'}})+line({timestamp:'2026-08-10T10:03:01Z',type:'response_item',payload:{type:'function_call_output',call_id:'call-1',output:'\u001b[31mOK\u001b[0m'}})+line({timestamp:'2026-08-10T10:03:02Z',type:'response_item',payload:{type:'reasoning',summary:[]}}),{flag:'a'});const events=await readRolloutEvents(path,id1);expect(events).toHaveLength(1);expect(events[0]).toMatchObject({type:'tool_call',content:'OK',metadata:{tool:'shell_command',arguments:{command:'pwd'},status:'completed'}})});
 it('discovers, sorts, isolates malformed files, deduplicates ids, and reads messages',async()=>{await rollout(id1,'10',root,'First prompt','Answer one');await rollout(id2,'11',root,'Newer prompt','Answer two');const bad=join(root,'sessions','2026','08','12');await mkdir(bad,{recursive:true});await writeFile(join(bad,'rollout-bad.jsonl'),'{bad json\n');await rollout(id1,'09',root,'Old duplicate','Old answer');const f=fixture(),t=await token(f),auth={Authorization:`Bearer ${t}`};const list=await f.api.get('/api/sessions').set(auth).expect(200);expect(list.body.map((s:any)=>s.session_id)).toEqual([id2,id1]);expect(list.body[0]).not.toHaveProperty('model');const detail=await f.api.get(`/api/sessions/${id2}`).set(auth).expect(200);expect(detail.body.messages.map((m:any)=>[m.role,m.content])).toEqual([['user','Newer prompt'],['assistant','Answer two']])});
 it('hides archived and deleted Codex Desktop threads from the session list',async()=>{const codexHome=join(root,'.codex'),sessionsDir=join(codexHome,'sessions'),visibleId='33333333-3333-4333-8333-333333333333',archivedId='44444444-4444-4444-8444-444444444444',deletedId='55555555-5555-4555-8555-555555555555',dir=join(sessionsDir,'2026','08','14');await mkdir(dir,{recursive:true});const desktopRollout=(id:string)=>line({timestamp:'2026-08-14T10:00:00Z',type:'session_meta',payload:{id,cwd:root,timestamp:'2026-08-14T10:00:00Z'}});await Promise.all([writeFile(join(dir,`rollout-${visibleId}.jsonl`),desktopRollout(visibleId)),writeFile(join(dir,`rollout-${archivedId}.jsonl`),desktopRollout(archivedId)),writeFile(join(dir,`rollout-${deletedId}.jsonl`),desktopRollout(deletedId))]);const desktopDb=new Database(join(codexHome,'state_5.sqlite'));desktopDb.exec('CREATE TABLE threads (id TEXT PRIMARY KEY, cwd TEXT, title TEXT, name TEXT, archived INTEGER NOT NULL, created_at_ms INTEGER, updated_at_ms INTEGER, recency_at_ms INTEGER)');const insert=desktopDb.prepare('INSERT INTO threads VALUES (?, ?, ?, ?, ?, ?, ?, ?)');insert.run(visibleId,root,'Visible',null,0,1,2,2);insert.run(archivedId,root,'Archived',null,1,1,2,2);desktopDb.close();const backups=join(root,'.codex-session-delete','backups');await mkdir(backups,{recursive:true});await writeFile(join(backups,'deleted.json'),JSON.stringify({session_id:deletedId}));const config=loadConfig({databasePath:':memory:',secret:'x'.repeat(32),codexHome,codexSessionsDir:sessionsDir,codexCommand:join(root,'missing-codex.exe'),codexCwdAllowlist:[root],codexRequestTimeoutMs:100});store=new Store(':memory:');const sessions=await new SessionService(store,config).list();expect(sessions.map(session=>session.session_id)).toEqual([visibleId])});
 it('merges overlays and rejects provider fields, fake creation, approvals, and bad cursors',async()=>{await rollout(id1,'10',root,'Prompt','Answer');const f=fixture(),t=await token(f),auth={Authorization:`Bearer ${t}`};await f.api.patch(`/api/sessions/${id1}`).set(auth).send({title:'Pinned',pinned:true}).expect(200);expect((await f.api.get('/api/sessions').set(auth)).body[0]).toMatchObject({title:'Pinned',pinned:true});await f.api.patch(`/api/sessions/${id1}`).set(auth).send({model:'claude'}).expect(400);await f.api.post('/api/sessions').set(auth).send({model:'codex'}).expect(400);await f.api.post('/api/sessions').set(auth).send({cwd:root,runtime:{sandbox:'danger-full-access'}}).expect(400);await f.api.post(`/api/sessions/${id1}/approvals`).set(auth).send({}).expect(404);await f.api.get('/api/sync?cursor=nope').set(auth).expect(400);await f.api.post(`/api/sessions/${id1}/messages`).set(auth).send({content:'hello'}).expect(503)});
 it('supports explicit refresh and authentication',async()=>{const f=fixture();await f.api.get('/api/sessions').expect(401);const t=await token(f),auth={Authorization:`Bearer ${t}`};expect((await f.api.get('/api/sessions').set(auth)).body).toEqual([]);await rollout(id1,'10',root,'Prompt','Answer');expect((await f.api.post('/api/sessions/refresh').set(auth).expect(200)).body).toHaveLength(1)})
 it('allows Capacitor WebView origins by default',async()=>{const f=fixture();const response=await f.api.get('/health').set('Origin','capacitor://localhost').expect(200);expect(response.headers['access-control-allow-origin']).toBe('capacitor://localhost')})
 it('lists approvals without leaking correlation internals and validates decisions',async()=>{await rollout(id1,'10',root,'Prompt','Answer');const f=fixture(),t=await token(f),auth={Authorization:`Bearer ${t}`};store.addApproval({requestId:'approval-1',rawId:7,epoch:Number.MAX_SAFE_INTEGER,threadId:id1,turnId:'turn-1',itemId:'item-1',kind:'item/commandExecution/requestApproval',payload:{command:'npm test'}});const list=await f.api.get(`/api/approvals?session_id=${id1}`).set(auth).expect(200);expect(list.body).toHaveLength(1);expect(list.body[0]).toMatchObject({request_id:'approval-1',session_id:id1,status:'pending'});expect(list.body[0]).not.toHaveProperty('raw_id');expect(list.body[0]).not.toHaveProperty('epoch');await f.api.post('/api/approvals/approval-1/decision').set(auth).send({decision:'yes'}).expect(400);await f.api.post('/api/approvals/missing/decision').set(auth).send({decision:'accept'}).expect(404)})
 it('invalidates access and refresh tokens after device revocation',async()=>{const f=fixture();const t=await token(f),auth={Authorization:`Bearer ${t}`};expect((await f.api.get('/api/sessions').set(auth)).status).toBe(200);await f.api.delete('/api/auth/device').set(auth).expect(204);await f.api.get('/api/sessions').set(auth).expect(401);const refresh=await f.api.post('/api/auth/refresh').send({device_id:(f as any).device_id,refresh_token:(f as any).refresh_token});expect(refresh.status).toBe(401)})
 it('returns reset flag when client cursor is ahead of the server',async()=>{const f=fixture(),t=await token(f),auth={Authorization:`Bearer ${t}`};const result=await f.api.get('/api/sync?cursor=999').set(auth).expect(200);expect(result.body).toMatchObject({cursor:0,events:[],reset:true,has_more:false})})
 it('returns reset when the client belongs to a previous event stream',async()=>{const f=fixture(),t=await token(f),auth={Authorization:`Bearer ${t}`};const current=await f.api.get('/api/sync?cursor=0').set(auth).expect(200);expect(current.body.stream_id).toMatch(/^[0-9a-f-]{36}$/);const result=await f.api.get('/api/sync?cursor=0&stream_id=22222222-2222-4222-8222-222222222222').set(auth).expect(200);expect(result.body).toMatchObject({reset:true,stream_id:current.body.stream_id})})
 });
