import type { Server } from 'node:http';import { WebSocketServer,WebSocket } from 'ws';import type { BridgeEvent,WsEnvelope } from '@remote/shared';import type { AuthService } from './auth.js';import type { Store } from './db.js';
const HEARTBEAT_INTERVAL=15000;const MAX_MISSED_PINGS=3;
export function attachWs(server:Server,auth:AuthService,store:Store,allowedOrigins:string[]=[]){const wss=new WebSocketServer({noServer:true,clientTracking:true,maxPayload:16*1024*1024});const missedPings=new WeakMap<WebSocket,number>();const socketDevices=new WeakMap<WebSocket,string>();const deviceSockets=new Map<string,Set<WebSocket>>();
const revokeDevice=(deviceId:string)=>{for(const ws of deviceSockets.get(deviceId)??[])ws.terminate();deviceSockets.delete(deviceId)};auth.on('revoked',revokeDevice);
server.on('upgrade',(req,socket,head)=>{try{const url=new URL(req.url||'','http://localhost');const origin=req.headers.origin;const sameOrigin=!origin||new URL(origin).host===req.headers.host;if(url.pathname!=='/ws'||!sameOrigin&&!allowedOrigins.includes(origin!))throw 0;const deviceId=auth.verify(url.searchParams.get('token')||'').sub;wss.handleUpgrade(req,socket,head,ws=>{socketDevices.set(ws,deviceId);let sockets=deviceSockets.get(deviceId);if(!sockets)deviceSockets.set(deviceId,sockets=new Set());sockets.add(ws);wss.emit('connection',ws,req)})}catch{socket.write('HTTP/1.1 401 Unauthorized\r\n\r\n');socket.destroy()}});
wss.on('connection',ws=>{missedPings.set(ws,0);ws.on('pong',()=>{missedPings.set(ws,0)});ws.on('close',()=>{missedPings.delete(ws);const deviceId=socketDevices.get(ws);if(deviceId){const sockets=deviceSockets.get(deviceId);sockets?.delete(ws);if(sockets?.size===0)deviceSockets.delete(deviceId)}socketDevices.delete(ws)});ws.on('error',()=>missedPings.delete(ws));send(ws,{type:'hello',cursor:store.latestCursor(),stream_id:store.streamId,message:'connected'})});
const heartbeatTimer=setInterval(()=>{for(const ws of wss.clients){if(ws.readyState!==WebSocket.OPEN)continue;const missed=missedPings.get(ws)??0;if(missed>=MAX_MISSED_PINGS){ws.terminate();continue}missedPings.set(ws,missed+1);ws.ping()}},HEARTBEAT_INTERVAL);
return {publish(event:BridgeEvent){for(const ws of wss.clients)if(ws.readyState===WebSocket.OPEN)send(ws,{type:'event',event,cursor:event.seq})},close:()=>{auth.off('revoked',revokeDevice);clearInterval(heartbeatTimer);for(const ws of wss.clients)ws.close(1001,'server shutdown');wss.close()}};
function send(ws:WebSocket,msg:WsEnvelope){ws.send(JSON.stringify(msg))}
}
